name: Build and Push Multiarch Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract schemasheet version
        id: extract_version
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker build -t evoratools/schemasheets:temp .
          TAG=$(docker run --rm -v $(pwd):/workdir -u $(id -u):$(id -g) evoratools/schemasheets:temp pip --no-cache-dir show schemasheets | grep "Version:" | grep -Eo "[\.0-9]+")
          echo "VERSION=$TAG" >> $GITHUB_ENV

      - name: Build and Push Multiarch Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t evoratools/schemasheets:${{ env.VERSION }} \
            --push .
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t evoratools/schemasheets:EVORA_TAG${{ env.VERSION }} \
            --build-arg EVORA_TAG=true \
            --push .
