name: Build and Push Multiarch Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Manual trigger
  schedule: # Automatic monthly trigger
    - cron: '0 0 1 * *' # Runs at midnight on the first day of each month

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Extract schemasheet version
        id: extract_version
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker build -t evoratools/schemasheets:temp .
          VERSION=$(docker run --rm -v $(pwd):/workdir -u $(id -u):$(id -g) evoratools/schemasheets:temp pip --no-cache-dir show schemasheets | grep "Version:" | grep -Eo "[\.0-9]+")
          echo "VERSION=$VERSION" >> $GITHUB_ENV


      - name: Build and Push Multiarch Docker Image with last official schemasheets+LinkML versions
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t evoratools/schemasheets:${{ env.VERSION }} \
            -t evoratools/schemasheets:latest \
            --push .

