name: Build and Push Multiarch Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Extract schemasheet version
        id: extract_version
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker build -t evoratools/schemasheets:temp .
          VERSION=$(docker run --rm -v $(pwd):/workdir -u $(id -u):$(id -g) evoratools/schemasheets:temp pip --no-cache-dir show schemasheets | grep "Version:" | grep -Eo "[\.0-9]+")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # For details on embeded improvements see Dockerfile https://github.com/EVORA-project/schemasheets/blob/main/Dockerfile
      # and https://github.com/EVORA-project/linkml 
      - name: Build and Push Multiarch schemasheets EVORA image that embeds special fixes ahead of PR integration
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t evoratools/schemasheets:EVORA_${{ env.VERSION }} \
            --build-arg EVORA_TAG=true \
            --push .

      - name: Build and Push Multiarch Docker Image with last official schemasheets+LinkML versions
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t evoratools/schemasheets:${{ env.VERSION }} \
            -t evoratools/schemasheets:latest \
            --push .

